server:
  # 服务器端口
  port: 9001
  servlet:
    # 应用访问路径
    context-path: /
  tomcat:
    # tomcat编码
    uri-encoding: utf-8
    threads:
      # 最大线程数
      max: 100
      # tomcat 启动初始化线程数
      min-spare: 10

# 日志配置
#logging:
#  level:
#    com.chmorn: debug
#    org.springframework: info
#  file:
#    name: logs/download.log

#mybatis 配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.chmorn.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*.xml

# 日志配置
logging:
  level:
    com.chmorn: debug
    org.springframework: warn

spring:
  application:
    name: PtHelper
  datasource:
    druid:
    # 数据源基本配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: chenxu123
    # 数据源其他配置
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 5
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

app:
  video:
    qq:
      qqPath: D:/iqyvideo/qqvideo/
    iptv:
      hntv:
        hnPath: D:/iptv/hntv/
        hnPathHign: D:/iptv/hntv_high/
    ffmpegPath: D:/tools/ffmpeg/bin/ffmpeg.exe
    nodePath: D:/tools/nodejs/node-v12.16.2-win-x64/node.exe
    maxThreads: 4



